### ISSUE TITLE
관심 없는 상품 가리기 기능

### ISSUE THREAD

**Issue by NariP** [ha3158987/mister_camel#46]
### 관심 없는 상품 가리기 기능

- [ ] 관련 state, 함수 위치 조정
- [ ] 기능 추가

**Comment by ha3158987** [comment]
#47 이슈 관련 내용 구현하면서 발견한 로직이 겹치는 부분이 있습니다!

- 관심 없음 버튼을 클릭하면 isInterested가 false로 업데이트 된 정보가 localStorage에 새로이 저장이 되는데, **랜덤 상품 조회** 버튼을 누르고 상품카드를 클릭하면 localStorage 모든 상품의 isInterested가 true로 바뀌네요.
- 이 부분은 localStorage는 캐싱의 영역인 반면 products는 상태로 관리가 되고 있어서가 아닌가 싶습니다.
- products에서 관심없는상품들의 isInterested 밸류를 false로 바꾸는 로직이 필요한데, 이 부분이 46번 이슈의 로직이 겹칩니다. 
- 이 부분이 구현이 되면 localStorage에서 recentPage로 불러오는 로직은 이어서 추가하겠습니다!! 😃

**Comment by NariP** [comment]
@ha3158987 저도 그럼 저 부분이 개발된 다음에 해야겠네요 그럼 다른 부분부터 구현하도록 하겠습니다.
